# docker-compose up
app:
  image: ibmcom/swift-ubuntu:4.0
  volumes:
    - .:/cf-deployment-tracker-client-swift
  command: bash -c "cd /cf-deployment-tracker-client-swift && swift package clean && swift build && swift test"
